import os

code = """import 'package:flutter/material.dart';

class AppTranslations {
  static const List<Map<String, String>> supportedLanguages = [
    {"code": "en", "name": "English", "native": "English", "flag": "🇬🇧"},
    {"code": "hi", "name": "Hindi", "native": "हिन्दी", "flag": "🇮🇳"},
    {"code": "mr", "name": "Marathi", "native": "मराठी", "flag": "🇮🇳"},
    {"code": "pa", "name": "Punjabi", "native": "ਪੰਜਾਬੀ", "flag": "🇮🇳"},
  ];

  static const Map<String, Map<String, String>> _translations = {
    "en": {
      "app_title": "Pramaan",
      "weather_guide": "Farmer Weather & Spray Guide",
      "select_district": "Select Punjab District",
      "refresh": "Refresh",
      "live_weather": "LIVE WEATHER",
      "safe_to_spray": "PERFECT TIME TO SPRAY",
      "safe_to_spray_sub": "Calm winds and ideal conditions for maximum chemical absorption.",
      "spray_caution": "SPRAY WITH CAUTION",
      "spray_caution_sub": "Elevated wind or heat. Recommended to spray during early morning or evening.",
      "do_not_spray": "DO NOT SPRAY TODAY",
      "do_not_spray_sub": "High wind or rain risk. Spray droplets may drift or wash off.",
      "temp": "Temp",
      "wind": "Wind",
      "rain_risk": "Rain Risk",
      "absorption": "Absorption",
      "spray_absorption": "Spray Absorption",
      "absorption_val_optimal": "Excellent (Optimal)",
      "absorption_val_moderate": "Moderate",
      "absorption_desc_optimal": "Droplets will not evaporate fast",
      "absorption_desc_moderate": "Sun heat may evaporate droplets",
      "wind_speed": "Wind Speed",
      "wind_calm": "Calm",
      "wind_breezy": "Breezy",
      "wind_desc_calm": "Zero drift to nearby crops",
      "wind_desc_breezy": "Higher chemical drift hazard",
      "rain_chance": "Rain Chance",
      "rain_desc_safe": "No wash-off danger",
      "rain_desc_unsafe": "Rain may wash away chemical",
      "heat_sun": "Heat & Temperature",
      "pleasant": "Pleasant",
      "too_hot": "Too Hot",
      "heat_desc_safe": "Safe for foliage absorption",
      "heat_desc_hot": "Too hot; spray in evening",
      "farmer_advisory": "Important Farmer Advisory",
      "advisory_bullet_1": "Check lower wheat leaves for yellow rust stripes or early aphid colonies.",
      "advisory_bullet_2": "Always use a full 200 Litres of clean water per acre with flat fan nozzles.",
      "advisory_bullet_3": "Avoid foliar spraying between 12:00 PM – 3:30 PM during peak midday heat.",
      "best_spray_timings": "Best Spray Timings (Next 48 Hours)",
      "morning_slot": "Today Morning (06:30 – 10:00 AM)",
      "midday_slot": "Today Midday (11:30 AM – 03:30 PM)",
      "evening_slot": "Today Evening (04:00 – 07:00 PM)",
      "tomorrow_slot": "Tomorrow Morning (06:30 – 10:30 AM)",
      "best_time": "BEST TIME",
      "moderate": "MODERATE",
      "no_spray": "DO NOT SPRAY",
      "morning_reason": "Calm wind and optimal absorption window.",
      "midday_reason": "Midday heat causes rapid droplet evaporation.",
      "evening_reason": "Safe evening foliar window; honeybee activity subsided.",
      "tomorrow_reason": "Clear weather expected with low drift.",
      "crop_diseases": "Common Crop Diseases & Treatment",
      "wheat": "Wheat",
      "wheat_disease": "Yellow / Stripe Rust",
      "wheat_symptoms": "Yellow powder or striping on lower leaf surfaces",
      "wheat_medicine": "Tilt 25% EC (Propiconazole) @ 200 ml per Acre",
      "wheat_organic": "Bio-Sulfur Dusting or Trichoderma viride 1.0 kg/Acre",
      "cotton": "Cotton",
      "cotton_disease": "Whitefly & Leaf Curl",
      "cotton_symptoms": "White sucking insects on leaf underside and leaf curling",
      "cotton_medicine": "Pyriproxyfen 10% EC @ 400 ml or Pegasus @ 250 g",
      "cotton_organic": "Bio-Neem 10,000 PPM @ 400 ml + 16 Yellow Sticky Traps/Acre",
      "potato": "Potato",
      "potato_disease": "Late Blight",
      "potato_symptoms": "Water-soaked dark lesions on leaf edges under high humidity",
      "potato_medicine": "Mancozeb 75% WP @ 600 g per Acre",
      "potato_organic": "Copper Oxychloride 50% WP @ 500 g per Acre",
      "dose_label": "Recommended Dose:",
      "organic_label": "Organic Alternative:",
      "language": "Language",
      "select_language": "Select Language",
      "home": "Home",
      "journal": "Journal",
      "voice_log": "Voice Log",
      "pricing": "Buyer Pricing",
      "insights": "Efficacy",
      "spray_safe_badge": "SAFE TO SPRAY",
      "spray_caution_badge": "CAUTION",
      "spray_no_badge": "DO NOT SPRAY",
      "ask_pramaan": "Ask Pramaan AI",
      "scan_input": "Scan Input QR",
      "verified_label": "VERIFIED",
      "crop_doctor_title": "Crop Doctor AI",
      "crop_doctor_sub": "Pramaan AI • Real-Time Plant Pathology",
      "target_crop": "Target Crop:",
      "take_photo": "Take Photo",
      "gallery": "Gallery",
      "try_sample": "Try Sample",
      "recommended_spray": "Recommended Spray:",
      "field_action": "Field Action:",
      "desi_organic": "Desi/Organic:",
      "save_spray_record": "SAVE SPRAY RECORD IN JOURNAL",
      "match_label": "Match",
      "damage_label": "Damage",
      "urgency_label": "Urgency",
      "healthy_crop": "Healthy Crop",
      "disease_alert": "Disease Alert",
      "pest_alert": "Pest Alert",
      "moderate_risk": "Moderate Risk",
      "view_scientific": "🔬 View Scientific & Prevention Details",
      "align_camera": "📷 Align crop leaf or plant inside frame",
      "evidence_title": "Farm Evidence Log",
      "verified_badge": "VERIFIED (100%)",
      "digital_seal_title": "Digital Security Seal (Protected Record)",
      "digital_seal_sub": "✓ Tamper-proof & officially secured agricultural record",
      "trust_agent_title": "Farm Trust & Quality Verification",
      "completeness": "Information Accuracy",
      "consistency": "Quality Status",
      "consistent_safe": "ACCURATE (100%)",
      "warning_status": "NEEDS REVIEW",
      "all_checks_passed": "✓ All farm, dosage, and weather details checked & verified safely.",
      "detected_issues": "Items Requiring Farmer Confirmation:",
      "action_required": "Action Required",
      "confirm_btn": "Confirm & Accept",
      "recheck_btn": "LIVE RE-VERIFY DETAILS",
      "farm_details_title": "Farm & Spray Details",
      "plot_label": "Plot / Village",
      "date_time_label": "Date & Time",
      "weather_label": "Weather Conditions",
      "product_label": "Product Used",
      "dosage_label": "Dosage Applied",
      "download_pdf_btn": "DOWNLOAD 3-PAGE OFFICIAL PDF REPORT",
      "quick_evidence_capture": "Quick Evidence Capture",
      "voice_log_title": "Voice Log",
      "voice_log_sub": "Speak in Hindi, Marathi, Punjabi",
      "crop_camera_title": "Crop Camera",
      "crop_camera_sub": "AI Disease Diagnosis",
      "scan_bottle_title": "Scan Bottle",
      "scan_bottle_sub": "QR Authenticity Check",
      "new_spray_title": "New Spray Log",
      "new_spray_sub": "Record Dosage & PHI",
      "verified_field_logs": "Verified Field Evidence Logs",
      "view_all": "View All",
      "filter_all": "ALL",
      "filter_verified": "VERIFIED",
      "filter_pending": "PENDING",
      "filter_flagged": "NEEDS REVIEW",
      "evidence_pipeline_title": "Evidence Verification Pipeline",
    },
    "hi": {
      "app_title": "प्रमाण",
      "weather_guide": "किसान मौसम और स्प्रे गाइड",
      "select_district": "पंजाब का जिला चुनें",
      "refresh": "ताज़ा करें",
      "live_weather": "लाइव मौसम",
      "safe_to_spray": "स्प्रे के लिए सबसे सही समय",
      "safe_to_spray_sub": "हवा शांत है और दवा पत्तियों पर पूरा असर करेगी। (अनुकूल मौसम)",
      "spray_caution": "सावधानी से स्प्रे करें",
      "spray_caution_sub": "हवा या गर्मी अधिक है। सुबह जल्दी या शाम को स्प्रे करने की सलाह है।",
      "do_not_spray": "आज स्प्रे न करें",
      "do_not_spray_sub": "तेज़ हवा या बारिश का खतरा है। दवा उड़ने या धुलने का डर है।",
      "temp": "तापमान",
      "wind": "हवा",
      "rain_risk": "बारिश",
      "absorption": "असर",
      "spray_absorption": "दवा का असर",
      "absorption_val_optimal": "शानदार (उत्तम)",
      "absorption_val_moderate": "मध्यम",
      "absorption_desc_optimal": "दवा जल्दी नहीं सूखेगी",
      "absorption_desc_moderate": "तेज धूप में दवा उड़ सकती है",
      "wind_speed": "हवा की गति",
      "wind_calm": "शांत",
      "wind_breezy": "तेज",
      "wind_desc_calm": "दवा उड़ने का खतरा नहीं",
      "wind_desc_breezy": "दवा दूसरी फसलों पर उड़ सकती है",
      "rain_chance": "बारिश की संभावना",
      "rain_desc_safe": "दवा धुलने का कोई डर नहीं",
      "rain_desc_unsafe": "बारिश से दवा धुल सकती है",
      "heat_sun": "धूप और तापमान",
      "pleasant": "सुहावना",
      "too_hot": "बहुत गर्म",
      "heat_desc_safe": "फसल के लिए सुरक्षित मौसम",
      "heat_desc_hot": "गर्मी ज्यादा है; शाम को करें",
      "farmer_advisory": "किसान भाइयों के लिए जरूरी सलाह",
      "advisory_bullet_1": "गेहूं के निचले पत्तों पर पीली रतुआ या चेपा (माहू) की जांच करें।",
      "advisory_bullet_2": "1 एकड़ में पूरा 200 लीटर साफ पानी मिलाकर ही स्प्रे करें।",
      "advisory_bullet_3": "दोपहर 12:00 से 3:30 बजे तेज धूप में स्प्रे करने से बचें।",
      "best_spray_timings": "स्प्रे करने का सही समय (अगले 48 घंटे)",
      "morning_slot": "आज सुबह (06:30 - 10:00 बजे)",
      "midday_slot": "आज दोपहर (11:30 - 03:30 बजे)",
      "evening_slot": "आज शाम (04:00 - 07:00 बजे)",
      "tomorrow_slot": "कल सुबह (06:30 - 10:30 बजे)",
      "best_time": "सबसे सही समय",
      "moderate": "ठीक समय",
      "no_spray": "स्प्रे न करें",
      "morning_reason": "शांत हवा और दवा के अच्छे असर का समय।",
      "midday_reason": "तेज धूप से दवा जल्दी सूखकर उड़ जाती है।",
      "evening_reason": "शाम को मधुमक्खियां लौट जाती हैं, हवा शांत रहती है।",
      "tomorrow_reason": "साफ मौसम की संभावना है।",
      "crop_diseases": "मुख्य फसल रोग और इलाज",
      "wheat": "गेहूं",
      "wheat_disease": "पीला रतुआ (Yellow Rust)",
      "wheat_symptoms": "पत्तों पर पीले रंग की धूल या धारियां बनना",
      "wheat_medicine": "टिल्ट (Tilt 25% EC) @ 200 मि.ली. प्रति एकड़",
      "wheat_organic": "सल्फर डस्टिंग या ट्राइकोडर्मा 1 किलो",
      "cotton": "कपास/नरमा",
      "cotton_disease": "सफेद मक्खी और पत्ता मरोड़",
      "cotton_symptoms": "पत्तों के नीचे सफेद मक्खी और पत्तों का मुड़ना",
      "cotton_medicine": "पायरीप्रॉक्सीफेन @ 400 मि.ली. या पेगासस @ 250 ग्राम",
      "cotton_organic": "नीम तेल (Bio-Neem) @ 400 मि.ली. + 16 पीले ट्रैप",
      "potato": "आलू",
      "potato_disease": "पिछेता झुलसा रोग (Late Blight)",
      "potato_symptoms": "पत्तों के किनारों पर काले-भूरे धब्बे पड़ना",
      "potato_medicine": "मैंकोजेब (Mancozeb 75% WP) @ 600 ग्राम",
      "potato_organic": "कॉपर ऑक्सीक्लोराइड 500 ग्राम",
      "dose_label": "सिफारिश की गई दवा:",
      "organic_label": "जैविक/देसी समाधान:",
      "language": "भाषा",
      "select_language": "भाषा चुनें",
      "home": "होम",
      "journal": "जर्नल",
      "voice_log": "आवाज से दर्ज करें",
      "pricing": "खरीदार भाव",
      "insights": "फायदा/रिकवरी",
      "spray_safe_badge": "स्प्रे के लिए सही समय",
      "spray_caution_badge": "सावधानी",
      "spray_no_badge": "स्प्रे न करें",
      "ask_pramaan": "प्रमाण एआई से पूछें",
      "scan_input": "दवा का क्यूआर स्कैन करें",
      "verified_label": "सत्यापित",
      "crop_doctor_title": "फसल डॉक्टर AI",
      "crop_doctor_sub": "Pramaan AI • तुरंत बीमारी और कीट जांच",
      "target_crop": "लक्ष्य फसल:",
      "take_photo": "फोटो लें",
      "gallery": "गैलरी",
      "try_sample": "नमूना देखें",
      "recommended_spray": "अनुशंसित स्प्रे (दवा):",
      "field_action": "खेत में कार्रवाई:",
      "desi_organic": "देसी/जैविक:",
      "save_spray_record": "स्प्रे रिकॉर्ड खाते में दर्ज करें",
      "match_label": "सटीकता",
      "damage_label": "नुकसान",
      "urgency_label": "समय सीमा",
      "healthy_crop": "तंदुरुस्त फसल",
      "disease_alert": "रोग चेतावनी",
      "pest_alert": "कीट चेतावनी",
      "moderate_risk": "मध्यम जोखिम",
      "view_scientific": "🔬 वैज्ञानिक और रोकथाम विवरण देखें",
      "align_camera": "📷 फसल के पत्ते या पौधे को फ्रेम में रखें",
      "evidence_title": "खेती प्रमाण रिकॉर्ड",
      "verified_badge": "सत्यापित (100%)",
      "digital_seal_title": "डिजिटल सुरक्षा मुहर (सुरक्षित रिकॉर्ड)",
      "digital_seal_sub": "✓ यह रिकॉर्ड बदला नहीं जा सकता, पूर्ण सुरक्षित व प्रामाणिक है",
      "trust_agent_title": "किसान विश्वास एवं गुणवत्ता जांच",
      "completeness": "जानकारी शुद्धता",
      "consistency": "जांच दर्जा",
      "consistent_safe": "अचूक व सुरक्षित",
      "warning_status": "जांच आवश्यक",
      "all_checks_passed": "✓ सभी जानकारी (दवा, मात्रा, मौसम और फसल) सुरक्षित और सही पाई गई।",
      "detected_issues": "किसान द्वारा पुष्टि आवश्यक बातें:",
      "action_required": "कार्रवाई आवश्यक",
      "confirm_btn": "स्वीकार व पुष्टि करें",
      "recheck_btn": "लाइव पुनः जांच करें",
      "farm_details_title": "खेत और छिड़काव का विवरण",
      "plot_label": "प्लॉट / गांव",
      "date_time_label": "तारीख और समय",
      "weather_label": "मौसम की स्थिति",
      "product_label": "इस्तेमाल की गई दवा",
      "dosage_label": "छिड़काव की मात्रा",
      "download_pdf_btn": "3-पेज आधिकारिक PDF रिपोर्ट डाउनलोड करें",
      "quick_evidence_capture": "तुरंत सबूत दर्ज करें",
      "voice_log_title": "आवाज से दर्ज करें",
      "voice_log_sub": "हिंदी, मराठी, पंजाबी में बोलें",
      "crop_camera_title": "फसल कैमरा",
      "crop_camera_sub": "एआई बीमारी जांच",
      "scan_bottle_title": "बोतल स्कैन करें",
      "scan_bottle_sub": "असली/नकली दवा जांच",
      "new_spray_title": "नया स्प्रे रिकॉर्ड",
      "new_spray_sub": "मात्रा व समय दर्ज करें",
      "verified_field_logs": "सत्यापित खेती रिकॉर्ड",
      "view_all": "सभी देखें",
      "filter_all": "सभी",
      "filter_verified": "सत्यापित",
      "filter_pending": "लंबित",
      "filter_flagged": "जांच आवश्यक",
      "evidence_pipeline_title": "सबूत और गुणवत्ता सत्यापन",
    },
    "mr": {
      "app_title": "प्रमाण",
      "weather_guide": "शेतकरी हवामान व फवारणी मार्गदर्शक",
      "select_district": "पंजाबचा जिल्हा निवडा",
      "refresh": "ताजे करा",
      "live_weather": "थेट हवामान",
      "safe_to_spray": "फवारणीसाठी अगदी योग्य वेळ",
      "safe_to_spray_sub": "हवा शांत आहे आणि औषधाचा पानांवर पूर्ण परिणाम होईल.",
      "spray_caution": "काळजीपूर्वक फवारणी करा",
      "spray_caution_sub": "वारा किंवा उष्णता जास्त आहे. सकाळी किंवा संध्याकाळी फवारणी करा.",
      "do_not_spray": "आज फवारणी करू नका",
      "do_not_spray_sub": "जोराचा वारा किंवा पावसाचा धोका आहे. औषध वाहून जाण्याची शक्यता.",
      "temp": "तापमान",
      "wind": "वारा",
      "rain_risk": "पाऊस",
      "absorption": "असर",
      "spray_absorption": "औषधाचा प्रभाव",
      "absorption_val_optimal": "उत्कृष्ट (योग्य)",
      "absorption_val_moderate": "मध्यम",
      "absorption_desc_optimal": "औषध लवकर वाळणार नाही",
      "absorption_desc_moderate": "उन्हामुळे औषध उडून जाऊ शकते",
      "wind_speed": "वाऱ्याचा वेग",
      "wind_calm": "शांत",
      "wind_breezy": "वेगात",
      "wind_desc_calm": "औषध उडण्याचा धोका नाही",
      "wind_desc_breezy": "औषध इतर पिकांवर उडू शकते",
      "rain_chance": "पावसाची शक्यता",
      "rain_desc_safe": "औषध वाहून जाण्याची भीती नाही",
      "rain_desc_unsafe": "पावसामुळे औषध वाहून जाऊ शकते",
      "heat_sun": "उष्णता आणि तापमान",
      "pleasant": "आनंददायी",
      "too_hot": "खूप गरम",
      "heat_desc_safe": "पिकासाठी सुरक्षित हवामान",
      "heat_desc_hot": "उष्णता जास्त; संध्याकाळी फवारा",
      "farmer_advisory": "शेतकरी बांधवांसाठी महत्त्वाची सूचना",
      "advisory_bullet_1": "गव्हाच्या खालच्या पानांवर तांबेरा (रस्ट) किंवा मावा कीड तपासा.",
      "advisory_bullet_2": "१ एकरासाठी पूर्ण २०० लिटर स्वच्छ पाणी वापरूनच फवारणी करा.",
      "advisory_bullet_3": "दुपारी १२:०० ते ०३:३० वाजेदरम्यान तीव्र उन्हात फवारणी टाळा.",
      "best_spray_timings": "फवारणीची योग्य वेळ (पुढील ४८ तास)",
      "morning_slot": "आज सकाळी (०६:३० - १०:००)",
      "midday_slot": "आज दुपारी (११:३० - ०३:३०)",
      "evening_slot": "आज संध्याकाळी (०४:०० - ०७:००)",
      "tomorrow_slot": "उद्या सकाळी (०६:३० - १०:३०)",
      "best_time": "सर्वोत्तम वेळ",
      "moderate": "मध्यम वेळ",
      "no_spray": "फवारणी करू नका",
      "morning_reason": "शांत वारा आणि औषधाच्या पूर्ण शोषणाची वेळ.",
      "midday_reason": "दुपारच्या उन्हामुळे औषध लवकर उडून जाते.",
      "evening_reason": "संध्याकाळी मधमाश्या परत जातात, वारा शांत असतो.",
      "tomorrow_reason": "स्वच्छ हवामानाचा अंदाज आहे.",
      "crop_diseases": "पिकांचे मुख्य रोग आणि उपचार",
      "wheat": "गहू",
      "wheat_disease": "पिवळा तांबेरा (Yellow Rust)",
      "wheat_symptoms": "पानांवर पिवळी पावडर किंवा पट्टे दिसणे",
      "wheat_medicine": "टिल्ट (Tilt 25% EC) @ २०० मि.ली. प्रति एकर",
      "wheat_organic": "गंधक पावडर किंवा ट्रायकोडर्मा १ किलो",
      "cotton": "कापूस",
      "cotton_disease": "पांढरी माशी आणि पानांचे सुरकुतणे",
      "cotton_symptoms": "पानांच्या खाली पांढरी माशी आणि पाने मुरडणे",
      "cotton_medicine": "पायरीप्रॉक्सिफेन @ ४०० मि.ली. किंवा पेगासस २५० ग्रॅम",
      "cotton_organic": "कडुनिंब तेल (Bio-Neem) @ ४०० मि.ली. + १६ पिवळे ट्रॅप",
      "potato": "बटाटा",
      "potato_disease": "करपा रोग (Late Blight)",
      "potato_symptoms": "पानांच्या कडांवर काळे-तपकिरी डाग पडणे",
      "potato_medicine": "मॅन्कोझेब (Mancozeb 75% WP) @ ६०० ग्रॅम",
      "potato_organic": "कॉपर ऑक्सिक्लोराईड ५०० ग्रॅम",
      "dose_label": "शिफारस केलेले औषध:",
      "organic_label": "सेंद्रिय/देशी उपाय:",
      "language": "भाषा",
      "select_language": "भाषा निवडा",
      "home": "होम",
      "journal": "जर्नल",
      "voice_log": "आवाजाने नोंदवा",
      "pricing": "खरेदीदार दर",
      "insights": "फायदा/रिकव्हरी",
      "spray_safe_badge": "फवारणीसाठी योग्य वेळ",
      "spray_no_badge": "फवारणी करू नका",
      "ask_pramaan": "प्रमाण एआय ला विचारा",
      "scan_input": "औषधाचा क्यूआर स्कॅन करा",
      "verified_label": "प्रमाणित",
      "crop_doctor_title": "पीक डॉक्टर AI",
      "crop_doctor_sub": "Pramaan AI • रोग व कीड त्वरित निदान",
      "target_crop": "लक्ष्य पीक:",
      "take_photo": "फोटो काढा",
      "gallery": "गॅलरी",
      "try_sample": "नमुना पीक",
      "recommended_spray": "शिफारस केलेले औषध:",
      "field_action": "कृती सूचना:",
      "desi_organic": "देशी/सेंद्रिय:",
      "save_spray_record": "फवारणी नोंद डायरीत जतन करा",
      "match_label": "अचूकता",
      "damage_label": "नुकसान",
      "urgency_label": "तातडी",
      "healthy_crop": "निरोगी पीक",
      "disease_alert": "रोग इशारा",
      "pest_alert": "कीड इशारा",
      "moderate_risk": "मध्यम जोखीम",
      "view_scientific": "🔬 वैज्ञानिक व प्रतिबंधक माहिती पहा",
      "align_camera": "📷 पिकाचे पान किंवा झाड फ्रेममध्ये ठेवा",
      "evidence_title": "शेती पुरावा नोंद",
      "verified_badge": "प्रमाणित (100%)",
      "digital_seal_title": "डिजिटल सुरक्षा शिक्का (सुरक्षित नोंद)",
      "digital_seal_sub": "✓ ही नोंद बदलता येत नाही, पूर्ण सुरक्षित व अस्सल आहे",
      "trust_agent_title": "शेतकरी विश्वास व गुणवत्ता पडताळणी",
      "completeness": "माहितीची अचूकता",
      "consistency": "पडताळणी दर्जा",
      "consistent_safe": "अचूक व सुरक्षित",
      "warning_status": "तपासणी आवश्यक",
      "all_checks_passed": "✓ सर्व माहिती (औषध, प्रमाण, हवामान आणि पीक) सुरक्षित व अचूक आढळली.",
      "detected_issues": "शेतकऱ्याची पुष्टी आवश्यक असलेल्या बाबी:",
      "action_required": "आवश्यक कृती",
      "confirm_btn": "पुष्टी करा / स्वीकारा",
      "recheck_btn": "थेट माहितीची फेरतपासणी करा",
      "farm_details_title": "शेतातील व फवारणीचा तपशील",
      "plot_label": "प्लॉट / गाव",
      "date_time_label": "दिनांक व वेळ",
      "weather_label": "हवामानाची स्थिती",
      "product_label": "वापरलेले औषध",
      "dosage_label": "फवारणीचे प्रमाण",
      "download_pdf_btn": "३-पानी अधिकृत PDF अहवाल डाउनलोड करा",
      "quick_evidence_capture": "त्वरित पुरावा नोंदणी",
      "voice_log_title": "आवाज नोंद",
      "voice_log_sub": "मराठी, हिंदी किंवा इंग्रजीत बोला",
      "crop_camera_title": "पीक कॅमेरा",
      "crop_camera_sub": "एआय रोग निदान",
      "scan_bottle_title": "बाटली स्कॅन करा",
      "scan_bottle_sub": "अस्सल औषध तपासणी",
      "new_spray_title": "नवीन फवारणी नोंद",
      "new_spray_sub": "प्रमाण व कालावधी नोंदवा",
      "verified_field_logs": "प्रमाणित शेती पुरावे",
      "view_all": "सर्व पहा",
      "filter_all": "सर्व",
      "filter_verified": "प्रमाणित",
      "filter_pending": "प्रलंबित",
      "filter_flagged": "तपासणी आवश्यक",
      "evidence_pipeline_title": "पुरावे व गुणवत्ता पडताळणी",
    },
    "pa": {
      "app_title": "ਪ੍ਰਮਾਣ",
      "weather_guide": "ਕਿਸਾਨ ਮੌਸਮ ਤੇ ਸਪਰੇਅ ਸਲਾਹ",
      "select_district": "ਆਪਣਾ ਜ਼ਿਲ੍ਹਾ ਚੁਣੋ",
      "refresh": "ਤਾਜ਼ਾ ਕਰੋ",
      "live_weather": "ਲਾਈਵ ਮੌਸਮ",
      "safe_to_spray": "ਸਪਰੇਅ ਲਈ ਬਿਲਕੁਲ ਸਹੀ ਸਮਾਂ",
      "safe_to_spray_sub": "ਹਵਾ ਸ਼ਾਂਤ ਹੈ, ਦਵਾਈ ਪੱਤਿਆਂ 'ਤੇ ਪੂਰਾ ਅਸਰ ਕਰੇਗੀ। (ਸੁਰੱਖਿਅਤ ਸਮਾਂ)",
      "spray_caution": "ਧਿਆਨ ਨਾਲ ਸਪਰੇਅ ਕਰੋ",
      "spray_caution_sub": "ਹਵਾ ਜਾਂ ਗਰਮੀ ਵੱਧ ਹੈ, ਸਵੇਰੇ ਜਾਂ ਸ਼ਾਮ ਨੂੰ ਸਪਰੇਅ ਕਰੋ।",
      "do_not_spray": "ਅੱਜ ਸਪਰੇਅ ਨਾ ਕਰੋ",
      "do_not_spray_sub": "ਤੇਜ਼ ਹਵਾ ਜਾਂ ਮੀਂਹ ਕਾਰਨ ਦਵਾਈ ਖ਼ਰਾਬ ਹੋ ਸਕਦੀ ਹੈ।",
      "temp": "ਤਾਪਮਾਨ",
      "wind": "ਹਵਾ",
      "rain_risk": "ਮੀਂਹ",
      "absorption": "ਅਸਰ",
      "spray_absorption": "ਦਵਾਈ ਦਾ ਅਸਰ",
      "absorption_val_optimal": "ਸ਼ਾਨਦਾਰ (ਵਧੀਆ)",
      "absorption_val_moderate": "ਦਰਮਿਆਨਾ",
      "absorption_desc_optimal": "ਦਵਾਈ ਜਲਦੀ ਨਹੀਂ ਸੁੱਕੇਗੀ",
      "absorption_desc_moderate": "ਧੁੱਪ ਵਿੱਚ ਦਵਾਈ ਉੱਡ ਸਕਦੀ ਹੈ",
      "wind_speed": "ਹਵਾ ਦੀ ਰਫ਼ਤਾਰ",
      "wind_calm": "ਸ਼ਾਂਤ",
      "wind_breezy": "ਤੇਜ਼",
      "wind_desc_calm": "ਦਵਾਈ ਉੱਡਣ ਦਾ ਕੋਈ ਖ਼ਤਰਾ ਨਹੀਂ",
      "wind_desc_breezy": "ਹਵਾ ਨਾਲ ਦਵਾਈ ਦੂਰ ਜਾ ਸਕਦੀ ਹੈ",
      "rain_chance": "ਮੀਂਹ ਦਾ ਖ਼ਤਰਾ",
      "rain_desc_safe": "ਦਵਾਈ ਧੁਲਣ ਦਾ ਕੋਈ ਡਰ ਨਹੀਂ",
      "rain_desc_unsafe": "ਮੀਂਹ ਨਾਲ ਦਵਾਈ ਧੁਲ ਸਕਦੀ ਹੈ",
      "heat_sun": "ਧੁੱਪ ਤੇ ਗਰਮੀ",
      "pleasant": "ਸੁਹਾਵਣਾ",
      "too_hot": "ਬਹੁਤ ਗਰਮ",
      "heat_desc_safe": "ਫਸਲ ਲਈ ਸੁਰੱਖਿਅਤ ਮੌਸਮ",
      "heat_desc_hot": "ਬਹੁਤ ਗਰਮ, ਸ਼ਾਮ ਨੂੰ ਕਰੋ",
      "farmer_advisory": "ਕਿਸਾਨ ਭਰਾਵਾਂ ਲਈ ਜ਼ਰੂਰੀ ਸਲਾਹ",
      "advisory_bullet_1": "ਕਣਕ 'ਤੇ ਪੀਲੀ ਕੁੰਗੀ ਜਾਂ ਤੇਲੇ ਦੇ ਹਮਲੇ ਦੀ ਜਾਂਚ ਹੇਠਲੇ ਪੱਤਿਆਂ ਤੋਂ ਕਰੋ।",
      "advisory_bullet_2": "1 ਏਕੜ ਵਿੱਚ ਪੂਰਾ 200 ਲੀਟਰ ਸਾਫ਼ ਪਾਣੀ ਮਿਲਾ ਕੇ ਹੀ ਸਪਰੇਅ ਕਰੋ।",
      "advisory_bullet_3": "ਦੁਪਹਿਰ 12:00 ਤੋਂ 3:30 ਵਜੇ ਤੇਜ਼ ਧੁੱਪ ਵਿੱਚ ਸਪਰੇਅ ਕਰਨ ਤੋਂ ਬਚੋ।",
      "best_spray_timings": "ਸਪਰੇਅ ਦਾ ਸਹੀ ਸਮਾਂ (ਅਗਲੇ 48 ਘੰਟੇ)",
      "morning_slot": "ਅੱਜ ਸਵੇਰੇ (06:30 - 10:00 ਵਜੇ)",
      "midday_slot": "ਅੱਜ ਦੁਪਹਿਰੇ (11:30 - 03:30 ਵਜੇ)",
      "evening_slot": "ਅੱਜ ਸ਼ਾਮ (04:00 - 07:00 ਵਜੇ)",
      "tomorrow_slot": "ਕੱਲ੍ਹ ਸਵੇਰੇ (06:30 - 10:30 ਵਜੇ)",
      "best_time": "ਸਭ ਤੋਂ ਵਧੀਆ ਸਮਾਂ",
      "moderate": "ਠੀਕ ਸਮਾਂ",
      "no_spray": "ਸਪਰੇਅ ਨਾ ਕਰੋ",
      "morning_reason": "ਹਵਾ ਸ਼ਾਂਤ ਹੈ, ਦਵਾਈ ਦਾ ਪੂਰਾ ਅਸਰ ਹੋਵੇਗਾ।",
      "midday_reason": "ਤੇਜ਼ ਧੁੱਪ ਤੇ ਗਰਮੀ ਕਾਰਨ ਦਵਾਈ ਉੱਡ ਸਕਦੀ ਹੈ।",
      "evening_reason": "ਸ਼ਾਮ ਨੂੰ ਮਧੂ-ਮੱਖੀਆਂ ਵਾਪਸ ਚਲੀਆਂ ਜਾਂਦੀਆਂ ਹਨ।",
      "tomorrow_reason": "ਮੌਸਮ ਸਾਫ਼ ਰਹਿਣ ਦੀ ਉਮੀਦ ਹੈ।",
      "crop_diseases": "ਮੁੱਖ ਬਿਮਾਰੀਆਂ ਤੇ ਦਵਾਈਆਂ",
      "wheat": "ਕਣਕ",
      "wheat_disease": "ਪੀਲੀ ਕੁੰਗੀ (Yellow Rust)",
      "wheat_symptoms": "ਪੱਤਿਆਂ 'ਤੇ ਪੀਲੇ ਰੰਗ ਦੀ ਧੂੜ ਜਾਂ ਪੱਟੀਆਂ ਬਣਨਾ",
      "wheat_medicine": "ਟਿਲਟ (Tilt 25% EC) @ 200 ਮਿ.ਲੀ. ਪ੍ਰਤੀ ਏਕੜ",
      "wheat_organic": "ਗੰਧਕ ਦੀ ਧੂੜ ਜਾਂ ਟਰਾਈਕੋਡਰਮਾ 1 ਕਿਲੋ",
      "cotton": "ਨਰਮਾ/ਕਪਾਹ",
      "cotton_disease": "ਚਿੱਟੀ ਮੱਖੀ ਤੇ ਪੱਤਾ ਮਰੋੜ",
      "cotton_symptoms": "ਪੱਤੇ ਥੱਲੇ ਚਿੱਟੇ ਕੀੜੇ ਅਤੇ ਪੱਤਿਆਂ ਦਾ ਮੁੜਨਾ",
      "cotton_medicine": "ਪਾਇਰੀਪ੍ਰੋਕਸੀਫੇਨ @ 400 ਮਿ.ਲੀ. ਜਾਂ ਪੈਗਾਸਸ @ 250 ਗ੍ਰਾਮ",
      "cotton_organic": "ਨੀਮ ਦਾ ਤੇਲ (Bio-Neem) @ 400 ਮਿ.ਲੀ. + 16 ਪੀਲੇ ਟਰੈਪ",
      "potato": "ਆਲੂ",
      "potato_disease": "ਪਛੇਤਾ ਝੁਲਸ ਰੋਗ (Late Blight)",
      "potato_symptoms": "ਪੱਤਿਆਂ ਦੇ ਕਿਨਾਰਿਆਂ 'ਤੇ ਕਾਲੇ-ਭੂਰੇ ਧੱਬੇ ਪੈਣਾ",
      "potato_medicine": "ਮੈਂਕੋਜ਼ੇਬ (Mancozeb 75% WP) @ 600 ਗ੍ਰਾਮ",
      "potato_organic": "ਕਾਪਰ ਆਕਸੀਕਲੋਰਾਈਡ 500 ਗ੍ਰਾਮ",
      "dose_label": "ਸਿਫ਼ਾਰਸ਼ ਕੀਤੀ ਦਵਾਈ:",
      "organic_label": "ਦੇਸੀ/ਜੈਵਿਕ ਹੱਲ:",
      "language": "ਭਾਸ਼ਾ",
      "select_language": "ਭਾਸ਼ਾ ਚੁਣੋ",
      "home": "ਹੋਮ",
      "journal": "ਜਰਨਲ",
      "voice_log": "ਬੋਲ ਕੇ ਦਰਜ ਕਰੋ",
      "pricing": "ਖ਼ਰੀਦਦਾਰ ਭਾਅ",
      "insights": "ਅਸਰ/ਮੁਨਾਫ਼ਾ",
      "spray_safe_badge": "ਸਪਰੇਅ ਲਈ ਸਹੀ ਸਮਾਂ",
      "spray_no_badge": "ਸਪਰੇਅ ਨਾ ਕਰੋ",
      "ask_pramaan": "ਪ੍ਰਮਾਣ ਏਆਈ ਨੂੰ ਪੁੱਛੋ",
      "scan_input": "ਦਵਾਈ ਦਾ QR ਸਕੈਨ ਕਰੋ",
      "verified_label": "ਤਸਦੀਕਸ਼ੁਦਾ",
      "crop_doctor_title": "ਫ਼ਸਲ ਡਾਕਟਰ AI",
      "crop_doctor_sub": "Pramaan AI • ਤੁਰੰਤ ਬਿਮਾਰੀ ਤੇ ਕੀੜਿਆਂ ਦੀ ਜਾਂਚ",
      "target_crop": "ਟਾਰਗੇਟ ਫ਼ਸਲ:",
      "take_photo": "ਫੋਟੋ ਖਿੱਚੋ",
      "gallery": "ਗੈਲਰੀ",
      "try_sample": "ਨਮੂਨਾ ਫ਼ਸਲ",
      "recommended_spray": "ਸਿਫ਼ਾਰਸ਼ ਕੀਤੀ ਦਵਾਈ (ਸਪਰੇਅ):",
      "field_action": "ਖੇਤ ਵਿੱਚ ਕਾਰਵਾਈ:",
      "desi_organic": "ਦੇਸੀ/ਜੈਵਿਕ:",
      "save_spray_record": "ਸਪਰੇਅ ਰਿਕਾਰਡ ਖਾਤੇ ਵਿੱਚ ਦਰਜ ਕਰੋ",
      "match_label": "ਸਟੀਕਤਾ",
      "damage_label": "ਨੁਕਸਾਨ",
      "urgency_label": "ਸਮਾਂ ਸੀਮਾ",
      "healthy_crop": "ਤੰਦਰੁਸਤ ਫ਼ਸਲ",
      "disease_alert": "ਬਿਮਾਰੀ ਅਲਰਟ",
      "pest_alert": "ਕੀੜਿਆਂ ਦਾ ਅਲਰਟ",
      "moderate_risk": "ਦਰਮਿਆਨਾ ਜੋਖ਼ਮ",
      "view_scientific": "🔬 ਵਿਗਿਆਨਕ ਅਤੇ ਬਚਾਅ ਦੇ ਵੇਰਵੇ ਵੇਖੋ",
      "align_camera": "📷 ਫਸਲ ਦੇ ਪੱਤੇ ਜਾਂ ਬੂਟੇ ਨੂੰ ਫਰੇਮ ਵਿੱਚ ਰੱਖੋ",
      "evidence_title": "ਖੇਤੀ ਸਬੂਤ ਰਿਕਾਰਡ",
      "verified_badge": "ਤਸਦੀਕਸ਼ੁਦਾ (100%)",
      "digital_seal_title": "ਡਿਜੀਟਲ ਸੁਰੱਖਿਆ ਸੀਲ (ਸੁਰੱਖਿਅਤ ਰਿਕਾਰਡ)",
      "digital_seal_sub": "✓ ਇਹ ਰਿਕਾਰਡ ਬਦਲਿਆ ਨਹੀਂ ਜਾ ਸਕਦਾ, ਪੂਰੀ ਤਰ੍ਹਾਂ ਸੁਰੱਖਿਅਤ ਹੈ",
      "trust_agent_title": "ਕਿਸਾਨ ਭਰੋਸਾ ਅਤੇ ਗੁਣਵੱਤਾ ਜਾਂਚ",
      "completeness": "ਜਾਣਕਾਰੀ ਦੀ ਸ਼ੁੱਧਤਾ",
      "consistency": "ਗੁਣਵੱਤਾ ਸਥਿਤੀ",
      "consistent_safe": "ਸਹੀ ਤੇ ਸੁਰੱਖਿਅਤ",
      "warning_status": "ਜਾਂਚ ਦੀ ਲੋੜ",
      "all_checks_passed": "✓ ਸਾਰੀ ਜਾਣਕਾਰੀ (ਦਵਾਈ, ਮਾਤਰਾ, ਮੌਸਮ ਅਤੇ ਫਸਲ) ਸੁਰੱਖਿਅਤ ਤੇ ਸਹੀ ਪਾਈ ਗਈ।",
      "detected_issues": "ਕਿਸਾਨ ਦੀ ਪੁਸ਼ਟੀ ਦੀ ਲੋੜ ਵਾਲੀਆਂ ਗੱਲਾਂ:",
      "action_required": "ਲੋੜੀਂਦੀ ਕਾਰਵਾਈ",
      "confirm_btn": "ਪੁਸ਼ਟੀ ਕਰੋ",
      "recheck_btn": "ਮੁੜ ਲਾਈਵ ਜਾਂਚ ਕਰੋ",
      "farm_details_title": "ਖੇਤ ਅਤੇ ਸਪਰੇਅ ਦਾ ਵੇਰਵਾ",
      "plot_label": "ਪਲਾਟ / ਪਿੰਡ",
      "date_time_label": "ਮਿਤੀ ਅਤੇ ਸਮਾਂ",
      "weather_label": "ਮੌਸਮ ਦੀ ਸਥਿਤੀ",
      "product_label": "ਵਰਤੀ ਗਈ ਦਵਾਈ",
      "dosage_label": "ਸਪਰੇਅ ਦੀ ਮਾਤਰਾ",
      "download_pdf_btn": "3-ਪੰਨਿਆਂ ਦੀ ਸਰਕਾਰੀ PDF ਰਿਪੋਰਟ ਡਾਊਨਲੋਡ ਕਰੋ",
      "quick_evidence_capture": "ਤੁਰੰਤ ਸਬੂਤ ਦਰਜ ਕਰੋ",
      "voice_log_title": "ਬੋਲ ਕੇ ਦਰਜ ਕਰੋ",
      "voice_log_sub": "ਪੰਜਾਬੀ, ਹਿੰਦੀ ਜਾਂ ਅੰਗਰੇਜ਼ੀ ਵਿੱਚ ਬੋਲੋ",
      "crop_camera_title": "ਫ਼ਸਲ ਕੈਮਰਾ",
      "crop_camera_sub": "ਏਆਈ ਬਿਮਾਰੀ ਜਾਂਚ",
      "scan_bottle_title": "ਬੋਤਲ ਸਕੈਨ ਕਰੋ",
      "scan_bottle_sub": "ਅਸਲੀ ਦਵਾਈ ਜਾਂਚ",
      "new_spray_title": "ਨਵਾਂ ਸਪਰੇਅ ਰਿਕਾਰਡ",
      "new_spray_sub": "ਮਾਤਰਾ ਤੇ ਸਮਾਂ ਦਰਜ ਕਰੋ",
      "verified_field_logs": "ਤਸਦੀਕਸ਼ੁਦਾ ਖੇਤੀ ਰਿਕਾਰਡ",
      "view_all": "ਸਾਰੇ ਵੇਖੋ",
      "filter_all": "ਸਾਰੇ",
      "filter_verified": "ਤਸਦੀਕਸ਼ੁਦਾ",
      "filter_pending": "ਬਕਾਇਆ",
      "filter_flagged": "ਜਾਂਚ ਲੋੜੀਂਦੀ",
      "evidence_pipeline_title": "ਸਬੂਤ ਅਤੇ ਗੁਣਵੱਤਾ ਤਸਦੀਕ",
    }
  };

  static String text(BuildContext context, String key, [String defaultVal = ""]) {
    return _translations["en"]?[key] ?? defaultVal;
  }

  static String tr(String langCode, String key, [String defaultVal = ""]) {
    return _translations[langCode]?[key] ?? _translations["en"]?[key] ?? defaultVal;
  }

  static void showLanguageSelectorModal(BuildContext context, String currentLang, Function(String) onSelect) {
    showModalBottomSheet(
      context: context,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      backgroundColor: Colors.white,
      builder: (ctx) {
        return SafeArea(
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    const Icon(Icons.translate_rounded, color: Color(0xFF059669), size: 22),
                    const SizedBox(width: 8),
                    const Expanded(
                      child: Text(
                        "Select Language / भाषा चुनें",
                        style: TextStyle(fontSize: 15.5, fontWeight: FontWeight.bold, color: Color(0xFF0F172A)),
                        overflow: TextOverflow.ellipsis,
                      ),
                    ),
                    IconButton(
                      icon: const Icon(Icons.close_rounded, size: 20, color: Color(0xFF64748B)),
                      onPressed: () => Navigator.pop(ctx),
                    ),
                  ],
                ),
                const SizedBox(height: 12),
                ...supportedLanguages.map((lang) {
                  final isSelected = currentLang == lang["code"];
                  return Material(
                    color: Colors.transparent,
                    child: Container(
                      margin: const EdgeInsets.only(bottom: 8),
                      decoration: BoxDecoration(
                        color: isSelected ? const Color(0xFFECFDF5) : Colors.white,
                        borderRadius: BorderRadius.circular(12),
                        border: Border.all(
                          color: isSelected ? const Color(0xFF059669) : const Color(0xFFE2E8F0),
                          width: isSelected ? 1.5 : 1.0,
                        ),
                      ),
                      child: ListTile(
                        leading: Text(
                          lang["flag"] ?? "🌐",
                          style: const TextStyle(fontSize: 22),
                        ),
                        title: Text(
                          lang["native"] ?? "",
                          style: TextStyle(
                            fontSize: 15,
                            fontWeight: isSelected ? FontWeight.bold : FontWeight.w600,
                            color: isSelected ? const Color(0xFF065F46) : const Color(0xFF1E293B),
                          ),
                        ),
                        subtitle: Text(
                          lang["name"] ?? "",
                          style: const TextStyle(fontSize: 12, color: Color(0xFF64748B)),
                        ),
                        trailing: isSelected
                            ? const Icon(Icons.check_circle_rounded, color: Color(0xFF059669))
                            : null,
                        onTap: () {
                          onSelect(lang["code"] ?? "en");
                          Navigator.pop(ctx);
                        },
                      ),
                    ),
                  );
                }),
                const SizedBox(height: 8),
              ],
            ),
          ),
        );
      },
    );
  }
}
"""

with open(r"frontend/lib/core/localization/app_translations.dart", "w", encoding="utf-8") as f:
    f.write(code)
print("Updated app_translations.dart successfully")
